/* tslint:disable */
/* eslint-disable */
/**
 * MTSynergy Platform BFF API
 * Backend For Frontend API for Web and Mobile clients
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListInboxResponse,
} from '../models/index';
import {
    ListInboxResponseFromJSON,
    ListInboxResponseToJSON,
} from '../models/index';

export interface ApiV1InboxGetRequest {
    page?: number;
}

/**
 * 
 */
export class InboxApi extends runtime.BaseAPI {

    /**
     * List inbox items
     */
    async apiV1InboxGetRaw(requestParameters: ApiV1InboxGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListInboxResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/inbox`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListInboxResponseFromJSON(jsonValue));
    }

    /**
     * List inbox items
     */
    async apiV1InboxGet(requestParameters: ApiV1InboxGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListInboxResponse> {
        const response = await this.apiV1InboxGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
