/* tslint:disable */
/* eslint-disable */
/**
 * MTSynergy Platform BFF API
 * Backend For Frontend API for Web and Mobile clients
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDraftRequest,
  CreateDraftResponse,
} from '../models/index';
import {
    CreateDraftRequestFromJSON,
    CreateDraftRequestToJSON,
    CreateDraftResponseFromJSON,
    CreateDraftResponseToJSON,
} from '../models/index';

export interface ApiV1DraftsPostRequest {
    createDraftRequest: CreateDraftRequest;
}

/**
 * 
 */
export class PublishingApi extends runtime.BaseAPI {

    /**
     * Create a new draft
     */
    async apiV1DraftsPostRaw(requestParameters: ApiV1DraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDraftResponse>> {
        if (requestParameters['createDraftRequest'] == null) {
            throw new runtime.RequiredError(
                'createDraftRequest',
                'Required parameter "createDraftRequest" was null or undefined when calling apiV1DraftsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/drafts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDraftRequestToJSON(requestParameters['createDraftRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDraftResponseFromJSON(jsonValue));
    }

    /**
     * Create a new draft
     */
    async apiV1DraftsPost(requestParameters: ApiV1DraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDraftResponse> {
        const response = await this.apiV1DraftsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
