/* tslint:disable */
/* eslint-disable */
/**
 * MTSynergy Platform BFF API
 * Backend For Frontend API for Web and Mobile clients
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Platform } from './Platform';
import {
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
    PlatformToJSONTyped,
} from './Platform';

/**
 * 
 * @export
 * @interface InboxItem
 */
export interface InboxItem {
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    workspaceId: string;
    /**
     * 
     * @type {Platform}
     * @memberof InboxItem
     */
    platform: Platform;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    platformItemId: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    contentType: InboxItemContentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    status: InboxItemStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof InboxItem
     */
    createdAt: Date;
}


/**
 * @export
 */
export const InboxItemContentTypeEnum = {
    Comment: 'COMMENT',
    Message: 'MESSAGE',
    Mention: 'MENTION'
} as const;
export type InboxItemContentTypeEnum = typeof InboxItemContentTypeEnum[keyof typeof InboxItemContentTypeEnum];

/**
 * @export
 */
export const InboxItemStatusEnum = {
    New: 'NEW',
    Assigned: 'ASSIGNED',
    Resolved: 'RESOLVED',
    Spam: 'SPAM'
} as const;
export type InboxItemStatusEnum = typeof InboxItemStatusEnum[keyof typeof InboxItemStatusEnum];


/**
 * Check if a given object implements the InboxItem interface.
 */
export function instanceOfInboxItem(value: object): value is InboxItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('platformItemId' in value) || value['platformItemId'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function InboxItemFromJSON(json: any): InboxItem {
    return InboxItemFromJSONTyped(json, false);
}

export function InboxItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InboxItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspaceId'],
        'platform': PlatformFromJSON(json['platform']),
        'platformItemId': json['platformItemId'],
        'author': json['author'],
        'content': json['content'],
        'contentType': json['contentType'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function InboxItemToJSON(json: any): InboxItem {
    return InboxItemToJSONTyped(json, false);
}

export function InboxItemToJSONTyped(value?: InboxItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'platform': PlatformToJSON(value['platform']),
        'platformItemId': value['platformItemId'],
        'author': value['author'],
        'content': value['content'],
        'contentType': value['contentType'],
        'status': value['status'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

